name: CI-Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/cache@v2
        id: cache-dotnet
        with:
          path: ~/AppData/Local/Microsoft/dotnet
          key: ${{ runner.os }}-dotnet

      - uses: actions/setup-dotnet@v1
        if: steps.cache-dotnet.outputs.cache-hit != 'true'
        with:
          dotnet-version: '5.0.x'

      - uses: actions/setup-dotnet@v1
        if: steps.cache-dotnet.outputs.cache-hit != 'true'
        with:
          dotnet-version: '3.1.x'

      - name: Execute the build
        shell: cmd
        run: .\build.cmd
